ANNOUNCEMENT_CATEGORY = (
    ("EVENT", "EVENT"),
    ("NEW HIRE", "NEW HIRE"),
    ("EMPLOYEE EXIT", "EMPLOYEE EXIT"),
    ("PROMOTIONS", "PROMOTIONS"),
    ("OTHERS", "OTHERS"),
)

ANNOUNCEMENT_STATUS = (
    ("PUBLISHED", "PUBLISHED"),
    ("DRAFT", "DRAFT"),
    ("ARCHIVED", "ARCHIVED"),
)
