EMPLOYEE_STATUS_OPTIONS = (
    ("UNVERIFIED", "UNVERIFIED"),
    ("VERIFIED", "VERIFIED"),
    ("DEACTIVATED", "DEACTIVATED"),
)

INVITATION_STATUS_OPTIONS = (("PENDING", "PENDING"), ("COMPLETED", "COMPLETED"))

MARITAL_STATUS_OPTIONS = (("SINGLE", "SINGLE"), ("MARRIED", "MARRIED"))

EMPLOYMENT_STATUS_OPTIONS = (
    ("PROBATION", "PROBATION"),
    ("INTERN", "INTERN"),
    ("FULL TIME", "FULL TIME"),
)
