USER_ROLE = (
    ("SUPERADMIN", "SUPERADMIN"),
    ("HR_ADMIN", "HR_ADMIN"),
    ("EMPLOYEE", "EMPLOYEE"),
    ("EXECUTIVE", "EXECUTIVE"),
)

GENDER_OPTION = (("MALE", "MALE"), ("FEMALE", "FEMALE"))

TOKEN_TYPE = (
    ("ACCOUNT_VERIFICATION", "ACCOUNT_VERIFICATION"),
    ("PASSWORD_RESET", "PASSWORD_RESET"),
)
