SECTOR_OPTIONS = (
    ("PRIVATE", "PRIVATE"),
    ("PUBLIC", "PUBLIC"),
)

TYPE_OPTIONS = (("SINGLE", "SINGLE"), ("MULTIPLE", "MULTIPLE"))

PACKAGE_OPTIONS = (
    ("CORE HR", "CORE HR"),
    ("PAYROLL", "PAYROLL"),
    ("HR & PAYROLL", "HR & PAYROLL"),
)

STATUS_OPTIONS = (
    ("ACTIVE", "ACTIVE"),
    ("INACTIVE", "INACTIVE"),
    ("SUSPENDED", "SUSPENDED"),
    ("DEACTIVATED", "DEACTIVATED"),
)
