NOTIFICATION_TYPES = (
    ('LEAVE', 'LEAVE'),
    ('EXPENSE CLAIM', 'EXPENSE CLAIM'),
    ('PROFILE', 'PROFILE'),
    ('ANNOUNCEMENT', 'ANNOUNCEMENT')
)

NOTIFICATION_ACTIONS = (
    ('APPLIED', 'APPLIED'),
    ('APPROVED', 'APPROVED'),
    ('REQUESTED', 'REQUESTED'),
    ('UPDATED', 'UPDATED'),
    ('COMPLETED', 'COMPLETED'),
    ('CANCELLED', 'CANCELLED'),
    ('DECLINED', 'DECLINED'),
    ('ANNOUNCED', 'ANNOUNCED'),
)

NOTIFICATION_RECIPIENT = (
    ('ALL', 'ALL'),
    ('HR_ADMIN', 'HR_ADMIN'),
    ('SUPER_ADMIN', 'SUPER_ADMIN'),
    ('ACTOR', 'ACTOR'),
    ('HR_ADMIN & ACTOR', 'HR_ADMIN & ACTOR'),
)
